spin_manifest_version = 2

[application]
name = "byteport"
version = "0.1.0"
authors = ["Koosha Paridehpour <kooshapari@gmail.com>"]
description = "Test"

[[trigger.http]]
route = "/..."
component = "byteport"

[component.byteport]
source = "main.wasm"
files = ["odin-dash.zip"]
allowed_outbound_hosts =  ["https://*:*",["http://*.spin.internal"]
[component.byteport.build]
command = "tinygo test -target=wasip1"
watch = ["**/*.go", "go.mod"]
[component.byteport.tool.spin-test]
source = "test.wasm"
build= "tinygo test -target=wasip1"
workdir = "./"
